language: ruby
rvm:
  - 2.0.0
  - 2.1.0-p0
  - 2.1.8
  - 2.2.0-p0
  - 2.2.4
  - 2.3.0
  - jruby-9.0.5.0
  - rbx-3.19
matrix:
  allow_failures:
    - rvm: rbx-3.19
before_install: gem install bundler -v 1.11.2
addons:
    code_climate:
        repo_token: 9646aae52d1d1670d545c46bd94f5d86b92d516c5e3cb9890fcef62acc3a34b6
after_script: codeclimate-test-reporter
